### ISSUE TITLE
Bootstrapping your own Boxen

### ISSUE THREAD

**Issue by kylekthompson** [tarebyte/my-boxen#3]
@tarebyte 
Under Bootstrapping in the README,
`git clone https://github.com/tarebyte/our-boxen /opt/boxen/repo` 
should be either
`git clone https://github.com/tarebyte/my-boxen /opt/boxen/repo`
or
`git clone https://github.com/boxen/our-boxen /opt/boxen/repo`

**Comment by tarebyte** [comment]
pull requests are welcome :smile_cat:
